[build]
  # Build command
  command = "npm run build"
  
  # Directory that contains the deploy-ready HTML files
  publish = "build"
  
  # Production context settings
  [build.environment]
    NODE_VERSION = "20"
    NPM_VERSION = "10"
    NPM_FLAGS = "--legacy-peer-deps"

# SPA redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Static assets caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Service Worker
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"

# Manifest and icons
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Error pages
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 200